package com.dwy.logistics.mapper;

import com.dwy.logistics.model.entities.Car;
import com.dwy.logistics.model.entities.CarExample.Criteria;
import com.dwy.logistics.model.entities.CarExample.Criterion;
import com.dwy.logistics.model.entities.CarExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class CarSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String countByExample(CarExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("car");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String deleteByExample(CarExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("car");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String insertSelective(Car record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("car");
        
        if (record.getCarID() != null) {
            sql.VALUES("carID", "#{carID,jdbcType=INTEGER}");
        }
        
        if (record.getCarType() != null) {
            sql.VALUES("carType", "#{carType,jdbcType=VARCHAR}");
        }
        
        if (record.getVolume() != null) {
            sql.VALUES("volume", "#{volume,jdbcType=DOUBLE}");
        }
        
        if (record.getMinVolume() != null) {
            sql.VALUES("minVolume", "#{minVolume,jdbcType=DOUBLE}");
        }
        
        if (record.getMaxVolume() != null) {
            sql.VALUES("maxVolume", "#{maxVolume,jdbcType=DOUBLE}");
        }
        
        if (record.getHeight() != null) {
            sql.VALUES("height", "#{height,jdbcType=DOUBLE}");
        }
        
        if (record.getWidth() != null) {
            sql.VALUES("width", "#{width,jdbcType=DOUBLE}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String selectByExample(CarExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("carID");
        } else {
            sql.SELECT("carID");
        }
        sql.SELECT("carType");
        sql.SELECT("volume");
        sql.SELECT("minVolume");
        sql.SELECT("maxVolume");
        sql.SELECT("height");
        sql.SELECT("width");
        sql.FROM("car");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Car record = (Car) parameter.get("record");
        CarExample example = (CarExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("car");
        
        if (record.getCarID() != null) {
            sql.SET("carID = #{record.carID,jdbcType=INTEGER}");
        }
        
        if (record.getCarType() != null) {
            sql.SET("carType = #{record.carType,jdbcType=VARCHAR}");
        }
        
        if (record.getVolume() != null) {
            sql.SET("volume = #{record.volume,jdbcType=DOUBLE}");
        }
        
        if (record.getMinVolume() != null) {
            sql.SET("minVolume = #{record.minVolume,jdbcType=DOUBLE}");
        }
        
        if (record.getMaxVolume() != null) {
            sql.SET("maxVolume = #{record.maxVolume,jdbcType=DOUBLE}");
        }
        
        if (record.getHeight() != null) {
            sql.SET("height = #{record.height,jdbcType=DOUBLE}");
        }
        
        if (record.getWidth() != null) {
            sql.SET("width = #{record.width,jdbcType=DOUBLE}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("car");
        
        sql.SET("carID = #{record.carID,jdbcType=INTEGER}");
        sql.SET("carType = #{record.carType,jdbcType=VARCHAR}");
        sql.SET("volume = #{record.volume,jdbcType=DOUBLE}");
        sql.SET("minVolume = #{record.minVolume,jdbcType=DOUBLE}");
        sql.SET("maxVolume = #{record.maxVolume,jdbcType=DOUBLE}");
        sql.SET("height = #{record.height,jdbcType=DOUBLE}");
        sql.SET("width = #{record.width,jdbcType=DOUBLE}");
        
        CarExample example = (CarExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String updateByPrimaryKeySelective(Car record) {
        SQL sql = new SQL();
        sql.UPDATE("car");
        
        if (record.getCarType() != null) {
            sql.SET("carType = #{carType,jdbcType=VARCHAR}");
        }
        
        if (record.getVolume() != null) {
            sql.SET("volume = #{volume,jdbcType=DOUBLE}");
        }
        
        if (record.getMinVolume() != null) {
            sql.SET("minVolume = #{minVolume,jdbcType=DOUBLE}");
        }
        
        if (record.getMaxVolume() != null) {
            sql.SET("maxVolume = #{maxVolume,jdbcType=DOUBLE}");
        }
        
        if (record.getHeight() != null) {
            sql.SET("height = #{height,jdbcType=DOUBLE}");
        }
        
        if (record.getWidth() != null) {
            sql.SET("width = #{width,jdbcType=DOUBLE}");
        }
        
        sql.WHERE("carID = #{carID,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    protected void applyWhere(SQL sql, CarExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}