package com.dwy.logistics.mapper;

import com.dwy.logistics.model.entities.Code;
import com.dwy.logistics.model.entities.CodeExample;
import com.dwy.logistics.model.entities.CodeKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @SelectProvider(type=CodeSqlProvider.class, method="countByExample")
    long countByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @DeleteProvider(type=CodeSqlProvider.class, method="deleteByExample")
    int deleteByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @Delete({
        "delete from code",
        "where adcode = #{adcode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(CodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @Insert({
        "insert into code (adcode, name, ",
        "citycode)",
        "values (#{adcode,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{citycode,jdbcType=VARCHAR})"
    })
    int insert(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @InsertProvider(type=CodeSqlProvider.class, method="insertSelective")
    int insertSelective(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @SelectProvider(type=CodeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="adcode", property="adcode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="citycode", property="citycode", jdbcType=JdbcType.VARCHAR)
    })
    List<Code> selectByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @Select({
        "select",
        "adcode, name, citycode",
        "from code",
        "where adcode = #{adcode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="adcode", property="adcode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="citycode", property="citycode", jdbcType=JdbcType.VARCHAR)
    })
    Code selectByPrimaryKey(CodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @UpdateProvider(type=CodeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @UpdateProvider(type=CodeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @UpdateProvider(type=CodeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @Update({
        "update code",
        "set name = #{name,jdbcType=VARCHAR},",
          "citycode = #{citycode,jdbcType=VARCHAR}",
        "where adcode = #{adcode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Code record);
}