package com.dwy.logistics.mapper;

import com.dwy.logistics.model.entities.Goods;
import com.dwy.logistics.model.entities.GoodsExample;
import com.dwy.logistics.model.entities.GoodsKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @SelectProvider(type=GoodsSqlProvider.class, method="countByExample")
    long countByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @DeleteProvider(type=GoodsSqlProvider.class, method="deleteByExample")
    int deleteByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @Delete({
        "delete from goods",
        "where goodsID = #{goodsID,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(GoodsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @Insert({
        "insert into goods (goodsID, goodsName, ",
        "volume)",
        "values (#{goodsID,jdbcType=INTEGER}, #{goodsName,jdbcType=VARCHAR}, ",
        "#{volume,jdbcType=DOUBLE})"
    })
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @InsertProvider(type=GoodsSqlProvider.class, method="insertSelective")
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @SelectProvider(type=GoodsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="goodsID", property="goodsID", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="goodsName", property="goodsName", jdbcType=JdbcType.VARCHAR),
        @Result(column="volume", property="volume", jdbcType=JdbcType.DOUBLE)
    })
    List<Goods> selectByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @Select({
        "select",
        "goodsID, goodsName, volume",
        "from goods",
        "where goodsID = #{goodsID,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="goodsID", property="goodsID", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="goodsName", property="goodsName", jdbcType=JdbcType.VARCHAR),
        @Result(column="volume", property="volume", jdbcType=JdbcType.DOUBLE)
    })
    Goods selectByPrimaryKey(GoodsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @UpdateProvider(type=GoodsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Goods record, @Param("example") GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @UpdateProvider(type=GoodsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Goods record, @Param("example") GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @UpdateProvider(type=GoodsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @Update({
        "update goods",
        "set goodsName = #{goodsName,jdbcType=VARCHAR},",
          "volume = #{volume,jdbcType=DOUBLE}",
        "where goodsID = #{goodsID,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Goods record);
}