package com.dwy.logistics.mapper;

import com.dwy.logistics.model.entities.Transport;
import com.dwy.logistics.model.entities.TransportExample.Criteria;
import com.dwy.logistics.model.entities.TransportExample.Criterion;
import com.dwy.logistics.model.entities.TransportExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TransportSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String countByExample(TransportExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("transport");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String deleteByExample(TransportExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("transport");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String insertSelective(Transport record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("transport");
        
        if (record.getStartPlaceID() != null) {
            sql.VALUES("startPlaceID", "#{startPlaceID,jdbcType=VARCHAR}");
        }
        
        if (record.getEndPlaceID() != null) {
            sql.VALUES("endPlaceID", "#{endPlaceID,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsID() != null) {
            sql.VALUES("goodsID", "#{goodsID,jdbcType=INTEGER}");
        }
        
        if (record.getGoodsNumber() != null) {
            sql.VALUES("goodsNumber", "#{goodsNumber,jdbcType=INTEGER}");
        }
        
        if (record.getCarNumber() != null) {
            sql.VALUES("carNumber", "#{carNumber,jdbcType=INTEGER}");
        }
        
        if (record.getCarVolume() != null) {
            sql.VALUES("carVolume", "#{carVolume,jdbcType=DOUBLE}");
        }
        
        if (record.getTime() != null) {
            sql.VALUES("time", "#{time,jdbcType=DATE}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String selectByExample(TransportExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("startPlaceID");
        } else {
            sql.SELECT("startPlaceID");
        }
        sql.SELECT("endPlaceID");
        sql.SELECT("goodsID");
        sql.SELECT("goodsNumber");
        sql.SELECT("carNumber");
        sql.SELECT("carVolume");
        sql.SELECT("time");
        sql.FROM("transport");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Transport record = (Transport) parameter.get("record");
        TransportExample example = (TransportExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("transport");
        
        if (record.getStartPlaceID() != null) {
            sql.SET("startPlaceID = #{record.startPlaceID,jdbcType=VARCHAR}");
        }
        
        if (record.getEndPlaceID() != null) {
            sql.SET("endPlaceID = #{record.endPlaceID,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsID() != null) {
            sql.SET("goodsID = #{record.goodsID,jdbcType=INTEGER}");
        }
        
        if (record.getGoodsNumber() != null) {
            sql.SET("goodsNumber = #{record.goodsNumber,jdbcType=INTEGER}");
        }
        
        if (record.getCarNumber() != null) {
            sql.SET("carNumber = #{record.carNumber,jdbcType=INTEGER}");
        }
        
        if (record.getCarVolume() != null) {
            sql.SET("carVolume = #{record.carVolume,jdbcType=DOUBLE}");
        }
        
        if (record.getTime() != null) {
            sql.SET("time = #{record.time,jdbcType=DATE}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("transport");
        
        sql.SET("startPlaceID = #{record.startPlaceID,jdbcType=VARCHAR}");
        sql.SET("endPlaceID = #{record.endPlaceID,jdbcType=VARCHAR}");
        sql.SET("goodsID = #{record.goodsID,jdbcType=INTEGER}");
        sql.SET("goodsNumber = #{record.goodsNumber,jdbcType=INTEGER}");
        sql.SET("carNumber = #{record.carNumber,jdbcType=INTEGER}");
        sql.SET("carVolume = #{record.carVolume,jdbcType=DOUBLE}");
        sql.SET("time = #{record.time,jdbcType=DATE}");
        
        TransportExample example = (TransportExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    protected void applyWhere(SQL sql, TransportExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}