package com.dwy.logistics.mapper;

import com.dwy.logistics.model.entities.Transport;
import com.dwy.logistics.model.entities.TransportExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TransportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @SelectProvider(type=TransportSqlProvider.class, method="countByExample")
    long countByExample(TransportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @DeleteProvider(type=TransportSqlProvider.class, method="deleteByExample")
    int deleteByExample(TransportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @Insert({
        "insert into transport (startPlaceID, endPlaceID, ",
        "goodsID, goodsNumber, ",
        "carNumber, carVolume, ",
        "time)",
        "values (#{startPlaceID,jdbcType=VARCHAR}, #{endPlaceID,jdbcType=VARCHAR}, ",
        "#{goodsID,jdbcType=INTEGER}, #{goodsNumber,jdbcType=INTEGER}, ",
        "#{carNumber,jdbcType=INTEGER}, #{carVolume,jdbcType=DOUBLE}, ",
        "#{time,jdbcType=DATE})"
    })
    int insert(Transport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @InsertProvider(type=TransportSqlProvider.class, method="insertSelective")
    int insertSelective(Transport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @SelectProvider(type=TransportSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="startPlaceID", property="startPlaceID", jdbcType=JdbcType.VARCHAR),
        @Result(column="endPlaceID", property="endPlaceID", jdbcType=JdbcType.VARCHAR),
        @Result(column="goodsID", property="goodsID", jdbcType=JdbcType.INTEGER),
        @Result(column="goodsNumber", property="goodsNumber", jdbcType=JdbcType.INTEGER),
        @Result(column="carNumber", property="carNumber", jdbcType=JdbcType.INTEGER),
        @Result(column="carVolume", property="carVolume", jdbcType=JdbcType.DOUBLE),
        @Result(column="time", property="time", jdbcType=JdbcType.DATE)
    })
    List<Transport> selectByExample(TransportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @UpdateProvider(type=TransportSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Transport record, @Param("example") TransportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    @UpdateProvider(type=TransportSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Transport record, @Param("example") TransportExample example);
}