package com.dwy.logistics.model.entities;

public class Car extends CarKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carType
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.volume
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private Double volume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.minVolume
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private Double minVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.maxVolume
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private Double maxVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.height
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private Double height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.width
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private Double width;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carType
     *
     * @return the value of car.carType
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carType
     *
     * @param carType the value for car.carType
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.volume
     *
     * @return the value of car.volume
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public Double getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.volume
     *
     * @param volume the value for car.volume
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setVolume(Double volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.minVolume
     *
     * @return the value of car.minVolume
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public Double getMinVolume() {
        return minVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.minVolume
     *
     * @param minVolume the value for car.minVolume
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setMinVolume(Double minVolume) {
        this.minVolume = minVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.maxVolume
     *
     * @return the value of car.maxVolume
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public Double getMaxVolume() {
        return maxVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.maxVolume
     *
     * @param maxVolume the value for car.maxVolume
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setMaxVolume(Double maxVolume) {
        this.maxVolume = maxVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.height
     *
     * @return the value of car.height
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.height
     *
     * @param height the value for car.height
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.width
     *
     * @return the value of car.width
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public Double getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.width
     *
     * @param width the value for car.width
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setWidth(Double width) {
        this.width = width;
    }
}