package com.dwy.logistics.model.entities;

public class CarKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private Integer carID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carID
     *
     * @return the value of car.carID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public Integer getCarID() {
        return carID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carID
     *
     * @param carID the value for car.carID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setCarID(Integer carID) {
        this.carID = carID;
    }
}