package com.dwy.logistics.model.entities;

public class Goods extends GoodsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodsName
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.volume
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private Double volume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsName
     *
     * @return the value of goods.goodsName
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsName
     *
     * @param goodsName the value for goods.goodsName
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.volume
     *
     * @return the value of goods.volume
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public Double getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.volume
     *
     * @param volume the value for goods.volume
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setVolume(Double volume) {
        this.volume = volume;
    }
}