package com.dwy.logistics.model.entities;

public class GoodsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodsID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private Integer goodsID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsID
     *
     * @return the value of goods.goodsID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public Integer getGoodsID() {
        return goodsID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsID
     *
     * @param goodsID the value for goods.goodsID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setGoodsID(Integer goodsID) {
        this.goodsID = goodsID;
    }
}