package com.dwy.logistics.model.entities;

public class OrdersKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private Integer orderID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderID
     *
     * @return the value of orders.orderID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public Integer getOrderID() {
        return orderID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderID
     *
     * @param orderID the value for orders.orderID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setOrderID(Integer orderID) {
        this.orderID = orderID;
    }
}