package com.dwy.logistics.model.entities;

import java.util.Date;

public class Orders extends OrdersKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.startPlaceID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private String startPlaceID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.endPlaceID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private String endPlaceID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodsID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private Integer goodsID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodsNumber
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private Integer goodsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.time
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.startPlaceID
     *
     * @return the value of orders.startPlaceID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String getStartPlaceID() {
        return startPlaceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.startPlaceID
     *
     * @param startPlaceID the value for orders.startPlaceID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setStartPlaceID(String startPlaceID) {
        this.startPlaceID = startPlaceID == null ? null : startPlaceID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.endPlaceID
     *
     * @return the value of orders.endPlaceID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String getEndPlaceID() {
        return endPlaceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.endPlaceID
     *
     * @param endPlaceID the value for orders.endPlaceID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setEndPlaceID(String endPlaceID) {
        this.endPlaceID = endPlaceID == null ? null : endPlaceID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goodsID
     *
     * @return the value of orders.goodsID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public Integer getGoodsID() {
        return goodsID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goodsID
     *
     * @param goodsID the value for orders.goodsID
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setGoodsID(Integer goodsID) {
        this.goodsID = goodsID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goodsNumber
     *
     * @return the value of orders.goodsNumber
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public Integer getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goodsNumber
     *
     * @param goodsNumber the value for orders.goodsNumber
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setGoodsNumber(Integer goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.time
     *
     * @return the value of orders.time
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.time
     *
     * @param time the value for orders.time
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }
}