package com.dwy.logistics.model.entities;

public class Place extends PlaceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.name
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.lng
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private Double lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.lat
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    private Double lat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.name
     *
     * @return the value of place.name
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.name
     *
     * @param name the value for place.name
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.lng
     *
     * @return the value of place.lng
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.lng
     *
     * @param lng the value for place.lng
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.lat
     *
     * @return the value of place.lat
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.lat
     *
     * @param lat the value for place.lat
     *
     * @mbg.generated Fri Jan 08 16:16:33 CST 2021
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }
}