package com.dwy.logistics.model.entities;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

public class TransportKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport.transportID
     *
     * @mbg.generated Fri Jan 08 15:20:18 CST 2021
     */
    private Integer transportID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport.transportID
     *
     * @return the value of transport.transportID
     *
     * @mbg.generated Fri Jan 08 15:20:18 CST 2021
     */
    public Integer getTransportID() {
        return transportID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport.transportID
     *
     * @param transportID the value for transport.transportID
     *
     * @mbg.generated Fri Jan 08 15:20:18 CST 2021
     */
    public void setTransportID(Integer transportID) {
        this.transportID = transportID;
    }

    public static void main(String[] args) {
        List list = new ArrayList();
        List list1 = new ArrayList();
        Collections.addAll(list,1,2,3);
        Collections.addAll(list1,2,3,4);
        list.addAll(list1);

    }
}