package com.dwy.logistics.model.entities;

public class TransportKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport.transportID
     *
     * @mbg.generated Fri Jan 08 15:20:18 CST 2021
     */
    private Integer transportID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport.transportID
     *
     * @return the value of transport.transportID
     *
     * @mbg.generated Fri Jan 08 15:20:18 CST 2021
     */
    public Integer getTransportID() {
        return transportID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport.transportID
     *
     * @param transportID the value for transport.transportID
     *
     * @mbg.generated Fri Jan 08 15:20:18 CST 2021
     */
    public void setTransportID(Integer transportID) {
        this.transportID = transportID;
    }
}